name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run Chromatic
        uses: chromaui/action@8536229ee904071f8edce292596f6dbe0da96b9b # v12.1.1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
